system:
  name: "Vision Inspection System"
  version: "1.0.0"
  
camera:
  resolution: [640, 480]
  framerate: 30
  format: "RGB888"
  
database:
  type: "sqlite"
  path: "./database/vision.db"
  
storage:
  master_images: "./storage/master_images"
  image_history: "./storage/image_history"
  history_limit: 100
  
api:
  host: "0.0.0.0"
  port: 5000
  cors_origins: ["http://localhost:3000"]
  
gpio:
  outputs: [17, 18, 27, 22, 23, 24, 25, 8]
  busy_output: 17  # OUT1 - BUSY signal
  ok_output: 18    # OUT2 - OK signal
  ng_output: 27    # OUT3 - NG signal
  
logging:
  level: "INFO"
  file: "./logs/vision.log"

